---

- name: tareas de configuración previas a la instalación de Kubernetes
  hosts: all
  vars_files:
    - "group_vars/hosts.yaml"
  gather_facts: false
  roles:
    - { role: pre-deployment, become: yes }