---

- name: despliegue de una aplicación web con volúmenes (servidor master)
  hosts: master
  vars_files:
    - "group_vars/clonerepo.yaml"
  gather_facts: false
  roles:
    - { role: master-deploy-webapp, become: yes }