---

- name: establecer zona horaria
  command: timedatectl set-timezone Europe/Madrid

- name: instalar chrony
  dnf:
    name: chrony
    state: latest
  become: yes

- name: habilitar e iniciar chronyd
  systemd: 
    name: systemctl
    state: started
    enabled: yes
  become: yes

- name: habilitar ntp
  command: timedatectl set-ntp true

- name: desactivar SELinux
  command: sed -i s/=enforcing/=disabled/g /etc/selinux/config

- name: instalar paquete nfs-utils
  dnf:
    name: nfs-utils
    state: latest
  become: yes

- name: instalar paquete nfs4-acl-tools
  dnf:
    name: nfs4-acl-tools
    state: latest
  become: yes

- name: instalar paquete wget
  dnf:
    name: wget
    state: latest
  become: yes